-- Migration: Add stock column + categories table
-- Run this in Supabase SQL Editor BEFORE deploying

-- 1. Add stock column to products
alter table products add column if not exists stock integer default null;

-- 2. Create categories table
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  "sortOrder" integer not null default 0
);

-- 3. Security
alter table categories enable row level security;
revoke all on categories from anon, authenticated;

-- 4. Seed default categories (تورت = last)
insert into categories (name, "sortOrder") values
  ('حلويات شريف الزيني', 1),
  ('مخبوزات', 2),
  ('مشكل حلويات', 3),
  ('تورت', 99)
on conflict (name) do nothing;
