create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null default 0,
  "originalPrice" numeric,
  "offerActive" boolean not null default false,
  "variablePrice" boolean not null default false,
  available boolean not null default true,
  image text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

alter table products add column if not exists "originalPrice" numeric;
alter table products add column if not exists "offerActive" boolean not null default false;
alter table products add column if not exists stock integer default null;

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  "sortOrder" integer not null default 0
);

alter table categories enable row level security;
revoke all on categories from anon, authenticated;

insert into categories (name, "sortOrder") values
  ('حلويات شريف الزيني', 1),
  ('مخبوزات', 2),
  ('مشكل حلويات', 3),
  ('تورت', 99)
on conflict (name) do nothing;

insert into products (name, category, price, "variablePrice", available)
values
  ('قطعة جاتوه', 'حلويات شريف الزيني', 25, false, true),
  ('قطعة جاتوه دارك شوكلت', 'حلويات شريف الزيني', 65, false, true),
  ('تشيز روند كراميل', 'حلويات شريف الزيني', 70, false, true),
  ('تشيز روند فراولة', 'حلويات شريف الزيني', 70, false, true),
  ('تشيز روند نوتيلا', 'حلويات شريف الزيني', 70, false, true),
  ('تشيز روند بلوبيري', 'حلويات شريف الزيني', 70, false, true),
  ('تشيز كيك كراميل', 'حلويات شريف الزيني', 65, false, true),
  ('تشيز كيك فراولة', 'حلويات شريف الزيني', 65, false, true),
  ('تشيز كيك نوتيلا', 'حلويات شريف الزيني', 65, false, true),
  ('تشيز كيك بلوبيري', 'حلويات شريف الزيني', 65, false, true),
  ('اكلير عين جمل كراميل', 'حلويات شريف الزيني', 60, false, true),
  ('قطعة جاتوه موس', 'حلويات شريف الزيني', 50, false, true),
  ('بولة فرنساوي', 'حلويات شريف الزيني', 50, false, true),
  ('ديسباسيتو وسط', 'حلويات شريف الزيني', 90, false, true),
  ('ديسباسيتو صغيرة', 'حلويات شريف الزيني', 40, false, true),
  ('طاجن نوتيلا', 'حلويات شريف الزيني', 70, false, true),
  ('طاجن رتشاب', 'حلويات شريف الزيني', 65, false, true),
  ('مولتن كيك', 'حلويات شريف الزيني', 70, false, true),
  ('ام علي', 'حلويات شريف الزيني', 40, false, true),
  ('قشطوطة كراميل', 'حلويات شريف الزيني', 40, false, true),
  ('قشطوطة نوتيلا', 'حلويات شريف الزيني', 40, false, true),
  ('قشطوطة لوتس', 'حلويات شريف الزيني', 40, false, true),
  ('ميني اكلير', 'حلويات شريف الزيني', 150, false, true),
  ('روطب سويت نوتيلا', 'حلويات شريف الزيني', 65, false, true),
  ('روطب سويت كراميل', 'حلويات شريف الزيني', 65, false, true),
  ('روطب سويت بيستاشيو', 'حلويات شريف الزيني', 90, false, true),
  ('جوليانا (هرس جاتوه)', 'حلويات شريف الزيني', 20, false, true),
  ('كيلو ميني مخبوزات', 'مخبوزات', 180, false, true),
  ('مشبك كيلو', 'مخبوزات', 80, false, true),
  ('مشبك القرص', 'مخبوزات', 20, false, true),
  ('سميط', 'مخبوزات', 30, false, true),
  ('كيك عسل', 'حلويات شريف الزيني', 55, false, true),
  ('جاتوه براونز', 'حلويات شريف الزيني', 50, false, true),
  ('ميلفيه', 'حلويات شريف الزيني', 30, false, true),
  ('باتيه', 'مخبوزات', 25, false, true),
  ('كرواسون سادة', 'مخبوزات', 25, false, true),
  ('كرواسون نوتيلا', 'مخبوزات', 50, false, true),
  ('كرواسون لوتس', 'مخبوزات', 50, false, true),
  ('ميني بيتزا', 'مخبوزات', 25, false, true),
  ('رز بلبن عيش سرايا', 'حلويات شريف الزيني', 25, false, true),
  ('رز بلبن لوتس', 'حلويات شريف الزيني', 20, false, true),
  ('رز بلبن اوريو', 'حلويات شريف الزيني', 20, false, true),
  ('رز بلبن جيلي', 'حلويات شريف الزيني', 20, false, true),
  ('كيلو مشكل سوري', 'مشكل حلويات', 180, false, true),
  ('كيلو مشكل شرقي', 'مشكل حلويات', 220, false, true),
  ('باكيت فوليه', 'مشكل حلويات', 50, false, true),
  ('باكيت سمسمية', 'مشكل حلويات', 50, false, true)
on conflict do nothing;

create table if not exists orders (
  id bigint generated by default as identity primary key,
  "customerName" text not null,
  phone text not null,
  address text not null,
  notes text,
  items jsonb not null,
  subtotal numeric not null default 0,
  deposit numeric not null default 0,
  fee numeric not null default 0,
  "paymentMethod" text not null,
  "paymentNumber" text not null,
  "receiptImage" text,
  status text not null,
  "deliveryDate" text not null,
  "deliveryFee" numeric,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists settings (
  key text primary key,
  value text not null,
  "updatedAt" timestamptz not null default now()
);

create table if not exists password_audit (
  id bigint generated by default as identity primary key,
  "changedAt" timestamptz not null default now(),
  note text not null
);

alter table products enable row level security;
alter table orders enable row level security;
alter table settings enable row level security;
alter table password_audit enable row level security;

revoke all on products from anon, authenticated;
revoke all on orders from anon, authenticated;
revoke all on settings from anon, authenticated;
revoke all on password_audit from anon, authenticated;

insert into products (name, category, price, "variablePrice", available)
values
  ('قطعة جاتوه', 'حلويات شريف الزيني', 25, false, true),
  ('قطعة جاتوه دارك شوكلت', 'حلويات شريف الزيني', 65, false, true),
  ('تشيز روند كراميل', 'حلويات شريف الزيني', 70, false, true),
  ('تشيز روند فراولة', 'حلويات شريف الزيني', 70, false, true),
  ('تشيز روند نوتيلا', 'حلويات شريف الزيني', 70, false, true),
  ('تشيز روند بلوبيري', 'حلويات شريف الزيني', 70, false, true),
  ('تشيز كيك كراميل', 'حلويات شريف الزيني', 65, false, true),
  ('تشيز كيك فراولة', 'حلويات شريف الزيني', 65, false, true),
  ('تشيز كيك نوتيلا', 'حلويات شريف الزيني', 65, false, true),
  ('تشيز كيك بلوبيري', 'حلويات شريف الزيني', 65, false, true),
  ('اكلير عين جمل كراميل', 'حلويات شريف الزيني', 60, false, true),
  ('قطعة جاتوه موس', 'حلويات شريف الزيني', 50, false, true),
  ('بولة فرنساوي', 'حلويات شريف الزيني', 50, false, true),
  ('ديسباسيتو وسط', 'حلويات شريف الزيني', 90, false, true),
  ('ديسباسيتو صغيرة', 'حلويات شريف الزيني', 40, false, true),
  ('طاجن نوتيلا', 'حلويات شريف الزيني', 70, false, true),
  ('طاجن رتشاب', 'حلويات شريف الزيني', 65, false, true),
  ('مولتن كيك', 'حلويات شريف الزيني', 70, false, true),
  ('ام علي', 'حلويات شريف الزيني', 40, false, true),
  ('قشطوطة كراميل', 'حلويات شريف الزيني', 40, false, true),
  ('قشطوطة نوتيلا', 'حلويات شريف الزيني', 40, false, true),
  ('قشطوطة لوتس', 'حلويات شريف الزيني', 40, false, true),
  ('ميني اكلير', 'حلويات شريف الزيني', 150, false, true),
  ('روطب سويت نوتيلا', 'حلويات شريف الزيني', 65, false, true),
  ('روطب سويت كراميل', 'حلويات شريف الزيني', 65, false, true),
  ('روطب سويت بيستاشيو', 'حلويات شريف الزيني', 90, false, true),
  ('جوليانا (هرس جاتوه)', 'حلويات شريف الزيني', 20, false, true),
  ('كيلو ميني مخبوزات', 'مخبوزات', 180, false, true),
  ('مشبك كيلو', 'مخبوزات', 80, false, true),
  ('مشبك القرص', 'مخبوزات', 20, false, true),
  ('سميط', 'مخبوزات', 30, false, true),
  ('كيك عسل', 'حلويات شريف الزيني', 55, false, true),
  ('جاتوه براونز', 'حلويات شريف الزيني', 50, false, true),
  ('ميلفيه', 'حلويات شريف الزيني', 30, false, true),
  ('باتيه', 'مخبوزات', 25, false, true),
  ('كرواسون سادة', 'مخبوزات', 25, false, true),
  ('كرواسون نوتيلا', 'مخبوزات', 50, false, true),
  ('كرواسون لوتس', 'مخبوزات', 50, false, true),
  ('ميني بيتزا', 'مخبوزات', 25, false, true),
  ('رز بلبن عيش سرايا', 'حلويات شريف الزيني', 25, false, true),
  ('رز بلبن لوتس', 'حلويات شريف الزيني', 20, false, true),
  ('رز بلبن اوريو', 'حلويات شريف الزيني', 20, false, true),
  ('رز بلبن جيلي', 'حلويات شريف الزيني', 20, false, true),
  ('كيلو مشكل سوري', 'مشكل حلويات', 180, false, true),
  ('كيلو مشكل شرقي', 'مشكل حلويات', 220, false, true),
  ('باكيت فوليه', 'مشكل حلويات', 50, false, true),
  ('باكيت سمسمية', 'مشكل حلويات', 50, false, true)
on conflict do nothing;
